- contract/.tools-version
- contract/src/base/errors.cairo
- contract/src/base/types.cairo
- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
Reverts Web3Novalabs/nova-one#8
> Revert "feat: fix features"

- frontend/lib/helper.ts
- frontend/type/type.ts
close #38   and #28
```
const {
writeAsync,
writeIsPending,
isSuccess,
error
} = useContractWrite({
functionName: 'transfer',
args: [recipient, amount],
abi: contractABI,
contractAddress: '0x...'
});
```
> ft:write contract helper function

- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_predifi.cairo
close https://github.com/Web3Novalabs/predifi/issues/32
Implement functions:
get_all_pools
Test:
> feat: implement function to get all pools and test

- contract/src/base/errors.cairo
- contract/src/base/types.cairo
- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
To Close: #56
All required features have been implemented with approriate test cases
> feat: calculate odds and shares on vote

- contract/src/base/types.cairo
- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
This PR updates the pool ID generation mechanism by replacing sequential numbering with a randomly generated ID using a package, improving uniqueness and security. All relevant functions have been modified to accommodate this change, ensuring compatibility with the existing system, which previously relied on incrementing numbers. Comprehensive tests have been implemented to verify the correctness of this update. closes #61
> feat: random id for a pool closes #61 (PR #87)

- contract/.tool-versions
- contract/Scarb.lock
- contract/Scarb.toml
- contract/src/predifi.cairo
closes #92
Our Cairo contract codebase has been experiencing critical dependency management challenges that potentially impact project stability, build consistency, and development workflows.
This pull request addresses comprehensive dependency management improvements, focusing on:
- Resolving version conflicts
- Ensuring compatibility across the project's dependency ecosystem
- Implementing a more robust dependency management strategy
- Conducted thorough review of all project dependencies
- Normalized package versions to ensure compatibility
- Removed deprecated or unused dependencies
- Updated Cairo compiler to the latest stable version
- Synchronized Starknet library dependencies
- Ensured compatibility with current development tools
- Implemented strict version pinning
- Added …
> fix scarb issues

- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
> feat: implement get-pool-creator function

- contract/src/predifi.cairo
- Integrated OpenZeppelin’s `UpgradeableComponent` to enable seamless contract upgrades.  
- Implemented `IUpgradeable` interface, allowing controlled upgrades while maintaining state.  
- Introduced `upgradeable` substorage to manage upgrade-related data.  
- Added an `upgrade` function to update the contract’s `ClassHash` and track versioning.  
- Defined upgrade-related events to log upgrade actions.  
- Ensured smooth integration with existing contract logic for future flexibility.  
This update makes the contract upgradeable, allowing future improvements without redeploying from scratch.
> Added Upgradeability to the Contract Using OpenZeppelin Upgrades  

- contract/src/predifi.cairo
Reverts Web3Novalabs/predifi#103
> Revert "Added Upgradeability to the Contract Using OpenZeppelin Upgrades  "

- contract/src/validator.cairo
- This PR introduces the base traits for an Ase Validator contract designed to support proof of stake (PoS) validation for pool mechanisms. The implementation focuses on establishing the foundational structure without providing a complete implementation.
- Establish a standardized interface for validator contracts in our proof of stake ecosystem
- Create a flexible base structure that can be extended for specific validation requirements
- Prepare the groundwork for future pool validation implementations
Changes
- Introduced base traits for Ase Validator contract
- Defined core structural elements for proof of stake validation
- Ensured modularity and extensibility of the validator contract
- Validator registration mechanism
- Stake management interfaces
- Basic validation state tracking
- …
> feat: add validation

- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
Reverts Web3Novalabs/predifi#107
> Revert "feat: implemet function for random picking of validators"

- contract/src/STRK.cairo
- contract/src/interfaces/IERC20.cairo
- contract/src/interfaces/ipredifi.cairo
- contract/src/lib.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
Overview
This pull request enhances the collect_pool_creation_fee function by fully implementing the logic required to securely transfer STRK tokens from the pool creator to the contract. This upgrade is crucial for enforcing the economic model of the PrediFi platform, ensuring the proper, transparent collection of fees across protocol, creator, and validator roles.
Background & Context
Currently, the collect_pool_creation_fee function exists only as a placeholder, meaning that STRK token transfers and corresponding fee mechanisms are not active. Without this implementation:
Fee enforcement is compromised.
The protocol’s trustless and decentralized properties are weakened.
Pool creation and betting operations lack proper security checks regarding fee handling.
By completing this …
> feat: fully implemented erc20, with other important functions

- contract/.tool-versions
- contract/src/STRK.cairo
- contract/src/base/types.cairo
- contract/src/interfaces/ipredifi.cairo
- contract/src/predifi.cairo
- contract/tests/test_contract.cairo
> Feature: user stats

- contract/src/predifi.cairo
Implement Predifi smart contract core functionality
SCOPE:
Cairo smart contract implementation for the Predifi DeFi platform
CHANGES:
• Core Contract Files:
- predifi.Cairo: Main contract implementation
• Contract Components:
- Token Management System
- DeFi Operations
- State Management
- Core Business Logic
TECHNICAL DETAILS:
- Implemented core contract functions
- Set up the token management system
- Added utility functions for contract operations
- Configured contract state handling
- Implemented security measures
- Added contract interfaces
TESTING:
✓ Contract deployment
✓ Token operations
✓ State transitions
✓ Security validations
✓ Function interactions
SECURITY CONSIDERATIONS:
- Access control implementation
- State validation checks
- Secure token operations
- Protected contract …
>  created_pool

- contract/src/predifi.cairo
Reverts Web3Novalabs/predifi#141
> Revert " created_pool"

- src/base/errors.cairo
- src/predifi.cairo
- tests/test_contract.cairo
This PR refactors the error handling mechanism across the codebase by centralizing all error messages and codes into `errors.cairo`. Previously, errors were defined both in `errors.cairo` and manually inline within `predifi.cairo`, leading to duplication, inconsistency, and maintainability issues.
* All error codes and messages previously defined in `predifi.cairo` are now moved to `errors.cairo`.
* Error messages have been reviewed and updated for clarity and consistency. A unified naming convention has been applied.
* All `assert` statements and manual error messages across `predifi.cairo` (and related modules) have been updated to reference the centralized errors.
* Removed all inline error definitions and replaced them with imports from `errors.cairo`.
* Error codes/messages are now …
> Centralize and Synchronize Error Handling

- backend/.env.example
- backend/.gitignore
- backend/Cargo.lock
- backend/Cargo.toml
- backend/README.md
- backend/docker-compose.yml
- backend/src/config/db_config.rs
- backend/src/config/mod.rs
- backend/src/db/database.rs
- backend/src/db/mod.rs
- backend/src/main.rs
This PR implements a complete backend setup with the Axum web framework and PostgreSQL connection pooling using SQLx, addressing issue #178. The implementation provides a foundation for scalable database operations with proper connection management.
- **Axum Web Framework**: Configured minimal Axum server running on port 3000
- **PostgreSQL Connection Pooling**: Implemented using `sqlx::PgPool` for efficient database connection management
- **Environment Configuration**: Added configurable database settings via environment variables
- **Docker Integration**: Included PostgreSQL database setup with Docker Compose
```
backend/
├── src/
│   ├── config/
│   │   ├── mod.rs
│   │   └── db_config.rs          # Database configuration from env vars
│   ├── db/
│   │   ├── mod.rs
│   │   └── …
```
> Setup axum and database connection

- Makefile
integrates a make pr file file that runs the scarb fmt and snforge test and scarb build, this helpes with creating prs
closes #172
> integrate a make pr file

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/config/mod.rs
- backend/src/config/tracing.rs
- backend/src/db/database.rs
- backend/src/error.rs
- backend/src/lib.rs
- backend/src/main.rs
>  Implement Structured Logging with OpenTelemetry

- backend/Cargo.lock
- backend/Cargo.toml
- backend/migrations/20250724150300_init.sql
- backend/src/controllers/market_controller.rs
- backend/src/controllers/mod.rs
- backend/src/controllers/pool_controller.rs
- backend/src/db/database.rs
- backend/src/lib.rs
- backend/src/main.rs
- backend/src/models/market.rs
- backend/src/models/mod.rs
- backend/src/models/pool.rs
- backend/test/test_sqlx_integration.rs
This PR sets up the sqlx database for the prediction market platform using SQLx with PostgreSQL. It introduces the core data models, database migrations, and controller functions needed to manage markets, pools, and user interactions.
- **Added initial migration** (`20250724150300_init.sql`) with three core tables:
- `market_category` - Categorization of prediction markets
- `market` - Individual prediction markets with descriptions and category associations
- `pool` - Betting pools with comprehensive configuration (timing, options, fees, privacy)
- `user_pool` - User participation tracking with staked amounts
- **Market models** (`src/models/market.rs`):
- `Market` struct with name, description, and category relationships
- `MarketCategory` struct for market categorization
- **Pool …
> Setup sqlx database integration

- src/base/errors.cairo
- src/base/security.cairo
- src/predifi.cairo
- tests/integration_test.cairo
**Fix: Add Input Validation & Edge Case Handling (#212)**  
Adds comprehensive input validation across public functions:  
- Check `amount > 0`  
- Validate `pool_id` existence  
- Enforce valid `option` ranges  
- Handle invalid timestamps & boundary conditions  
- Improve error messages for clarity  
Includes a new **validation test suite** to cover zero/invalid inputs and edge cases.  
---
> [Mod]: : Missing Input Validation - Edge Case Handling
